=== pawelmiszkurka/web_data_playground/wdtma/recipes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--  
Module: Web Data with XML, JSON and AJAX
( Tutor Marked Assignment )
Date: 19 Jan 2017
Student: Pawel Miszkurka
Number: 130007376
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Definition of the root element  -->
<xs:element name="recipes">
   <xs:complexType>
	  <xs:sequence>
		 <xs:element name="recipe" type="recipeType" minOccurs="1" maxOccurs="unbounded" />
	  </xs:sequence>
	</xs:complexType>
</xs:element>

<!-- 
Definitions: 
	image, 
	title, 
	description, 
	prepTime, 
	cookingTime,
	servings,
	ingredients.
-->
<xs:complexType name="recipeType">
	<xs:sequence>
		
		<!-- Define simple elements with name -->
		<xs:element name="image" type="xs:string"/>
		<xs:element name="title" type="xs:string"/>
		<xs:element name="description" type="xs:string"/>
		
		<!-- Complex element which contains only attributes and text -->
		<xs:element name="prepTime">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:positiveInteger">
						<!-- 'unit' for the element: 'prepTime'. must be an integer -->
						<xs:attribute name="unit" use="required"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
		
		<!-- Complex element which contains only attributes and text -->
		<xs:element name="cookingTime" minOccurs="0">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:positiveInteger">
						<!-- 'cookingTime'. This attribute is required and must be an integer -->
						<xs:attribute name="unit" type="xs:string" use="required"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
		
		<!-- Allow only the following values to be entered for the recipe
		difficulty levels -->
		<xs:element name="difficulty">
			<xs:simpleType>
				<!-- Restrictions on values: Only the following enums are allowed. -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="Easy"/>
					<xs:enumeration value="More Effort"/>
					<xs:enumeration value="A Challenge"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		
		<!-- Complex element which contains attributes and text -->
		<xs:element name="servings">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string">
						<!-- This attribute is optional of type string.  -->
						<xs:attribute name="type" use="optional"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
		
		<!-- Define element of type 'ingredientType'.-->
		<xs:element name="ingredients" type="ingredientType" minOccurs="1" maxOccurs="unbounded"/>
		
	</xs:sequence>
	
	<!--  'id' for the element: 'servings'.  -->
	<xs:attribute name="id" type="xs:positiveInteger"/>
	
</xs:complexType>

<!-- 'ingredientType' -->
<xs:complexType name="ingredientType">
	<xs:sequence>
		<xs:element name="ingredient" minOccurs="1" maxOccurs="unbounded">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string">
						<!-- attributes for the element.  -->
						<xs:attribute name="amount" type="xs:decimal" use="optional"/>
						<xs:attribute name="unit" type="xs:string" use="optional"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== pawelmiszkurka/web_data_playground/wdtma/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  
Module: Web Data with XML, JSON and AJAX
( Tutor Marked Assignment )
Date: 19 Jan 2017
Student: Pawel Miszkurka
Number: 130007376
-->

<?xml-stylesheet type="text/xsl" href="http://titan.dcs.bbk.ac.uk/~pmiszk01/wd/wdtma/recipes.xsl"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://titan.dcs.bbk.ac.uk/~pmiszk01/wd/wdtma/recipes.xsd">
    <recipe id="1">
        <image>images/omlet.jpg</image>
        <title>Cheesy mushroom omelette</title>
        <description>Whip up a tasty omelette with this recipe</description>
        <prepTime unit="minutes">5</prepTime>
        <cookingTime unit="minutes">10</cookingTime>
		<difficulty>Easy</difficulty>
        <servings type="serving">Serves 1 person</servings>
        <ingredients> 
            <ingredient amount="1" unit="tbsp">Olive Oil</ingredient>
        	<ingredient amount="1">Handfull button or chestnut mushrooms, sliced</ingredient>
        	<ingredient amount="25" unit="grams">Vegetarian cheddar, grated</ingredient>
        	<ingredient amount="1">Small handful parsley leaves, roughly chopped</ingredient>
        	<ingredient amount="2">Eggs beaten</ingredient>
        </ingredients>        
    </recipe>
    <recipe id="2">
        <image>images/sirloin.jpg</image>
        <title>Roast sirloin of beef</title>
        <description>Gary Rhodes&apos; delicious, succulent roast beef dish is perfect for Boxing Day lunch or an alternative Christmas Day roast. Just four ingredients</description>
        <prepTime unit="minutes">10</prepTime>
        <cookingTime unit="minutes">150</cookingTime>
        <difficulty>Easy</difficulty>
        <servings type="serving">Serves 6 people</servings>
        <ingredients> 
            <ingredient amount="2" unit="tbsp">Vegetable oil or beef fat</ingredient>
            <ingredient amount="1.5" unit="kg">Sirloin of beef joint</ingredient>
            <ingredient amount="1" unit="glass">Red Wine</ingredient>
            <ingredient amount="400" unit="grams">Can beef cansome</ingredient>
        </ingredients>        
    </recipe>
    <recipe id="3">
        <image>images/haddock.jpg</image>
        <title>Haddock &amp; leek au gratin with sweetcorn mash</title>
        <description>Leek and spinach are layered up with white fish fillets and cheese sauce then topped with golden mash in this delicious, low-fat oven bake.</description>
        <prepTime unit="minutes">10</prepTime>
        <cookingTime unit="minutes">50</cookingTime>
        <difficulty>Easy</difficulty>
        <servings type="serving">Serves 2 people</servings>
        <ingredients> 
            <ingredient amount="350" unit="grams">Pottatoes quartered</ingredient>
            <ingredient amount="195">Can sweetcorn in water</ingredient>
            <ingredient amount="240" unit="grams">Bag ready-washed spinach</ingredient>
            <ingredient amount="2">Leeks, thickly sliced</ingredient>
            <ingredient amount="300" unit="ml">Skimmed milk</ingredient>
            <ingredient amount="15" unit="grams">Unsalted butter</ingredient>
            <ingredient amount="1.5">English Mustard</ingredient>
            <ingredient amount="75g" unit="grams">Mature reduced-fat cheese, grated</ingredient>
            <ingredient amount="250" unit="g">Fillets of skinless haddock</ingredient>
        </ingredients>        
    </recipe>
</recipes>
